### ISSUE TITLE
Fuses for the Atmel 

### ISSUE THREAD

**Issue by steamboating** [ClubNCaldes/GCA101LbServer#1]
I would like to load the HEX code into the chip via Atmel Studio. 

Usually at Atmel you have to set the FUSES. 

Where can I find this information for this project?

Thanks and regards
Rainer

**Comment by ClubNCaldes** [comment]
I'm not using Atmel Studio to upload de HEX, I'm not sure what fuses should be enable/disable, I just upload it with the fuses as set by default and it works...

**Comment by ClubNCaldes** [comment]
I checked how I burn it. I'm using myAVR ProgTook and I have the option "burning the fuses" disabled, so I'm not setting any fuse.

**Comment by ClubNCaldes** [comment]
I checked how I burn it. I'm using myAVR ProgTook and I have the option "burning the fuses" disabled, so I'm not setting any fuse.
